[package]
name = "hopr-types"
description = "Complete collection of Rust types used in Hoprnet and other related projects"

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
default = ["rayon"]
use-bindings = [
    "hopr-chain-types?/use-bindings"
]
fixed-rng = [
    "hopr-crypto-random?/fixed-rng",
    "hopr-crypto-types?/fixed-rng",
    "hopr-internal-types?/fixed-rng"
]
telemetry = [
    "hopr-parallelize?/telemetry"
]
rayon = [
    "hopr-internal-types?/rayon",
    "hopr-parallelize?/rayon",
]
runtime-tokio = [
    "hopr-parallelize?/runtime-tokio"
]
serde = [
    "hopr-crypto-types?/serde",
    "hopr-internal-types?/serde",
    "hopr-primitive-types?/serde"
]

chain = ["dep:hopr-chain-types"]
crypto = ["dep:hopr-crypto-types"]
internal = ["dep:hopr-internal-types"]
parallelize = ["dep:hopr-parallelize"]
primitive = ["dep:hopr-primitive-types"]
random = ["dep:hopr-crypto-random"]

[dependencies]
hopr-chain-types = { workspace = true, optional = true }
hopr-crypto-types = { workspace = true, optional = true }
hopr-internal-types = { workspace = true, optional = true }
hopr-parallelize = { workspace = true, optional = true }
hopr-primitive-types = { workspace = true, optional = true }
hopr-crypto-random = { workspace = true, optional = true }