[package]
name = "hopr-types"
version = "1.0.0"
description = "Complete collection of Rust types used in Hoprnet and other related projects"
homepage = "https://hoprnet.org/"
repository = "https://github.com/hoprnet/hoprnet"
license = "GPL-3.0-only"
edition.workspace = true
rust-version.workspace = true

[features]
default = ["rayon"]
fixed-rng = [
    "hopr-crypto-random?/fixed-rng",
    "hopr-crypto-types?/fixed-rng",
    "hopr-internal-types?/fixed-rng"
]
telemetry = [
    "hopr-parallelize?/telemetry"
]
rayon = [
    "hopr-internal-types?/rayon",
    "hopr-parallelize?/rayon",
]
runtime-tokio = [
    "hopr-parallelize?/runtime-tokio"
]
serde = [
    "hopr-crypto-types?/serde",
    "hopr-internal-types?/serde",
    "hopr-primitive-types?/serde"
]

chain = ["dep:hopr-chain-types"]
crypto = ["dep:hopr-crypto-types"]
internal = ["dep:hopr-internal-types"]
parallelize = ["dep:hopr-parallelize"]
primitive = ["dep:hopr-primitive-types"]
random = ["dep:hopr-crypto-random"]

[dependencies]
hopr-chain-types = { workspace = true, optional = true }
hopr-crypto-types = { workspace = true, optional = true }
hopr-internal-types = { workspace = true, optional = true }
hopr-parallelize = { workspace = true, optional = true }
hopr-primitive-types = { workspace = true, optional = true }
hopr-crypto-random = { workspace = true, optional = true }