[advisories]
ignore = [
    "RUSTSEC-2024-0388", # derivative: unmaintained, but widely used transitive dependency
    "RUSTSEC-2024-0436", # paste: unmaintained, but widely used transitive dependency
    "RUSTSEC-2026-0173", # proc-macro-error2: unmaintained, used by aquamarine and alloy
]
