[package]
name = "hopr-primitive-types"
description = "Generic types used through the entire code base"

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
crate-type = ["rlib"]

[features]
default = []
serde = ["dep:serde", "dep:serde_bytes", "chrono/serde", "primitive-types/serde"]

[dependencies]
bigdecimal = { workspace = true }
float-cmp = { workspace = true }
hex = { workspace = true }
lazy_static = { workspace = true }
primitive-types = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, optional = true }
serde_bytes = { workspace = true, optional = true }
sha3 = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
hex-literal = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["serde_bytes"]
