[package]
name = "hopr-crypto-types"
description = "Implements basic cryptograpic primitives and cryptography related types"

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
rust-ecdsa = []
fixed-rng = ["hopr-crypto-random/fixed-rng"]
serde = [
  "dep:serde",
  "dep:serde_bytes",
  "curve25519-dalek/serde",
  "ed25519-dalek/serde",
  "generic-array/serde",
  "k256/serde",
  "libp2p-identity/serde",
]
allocator-mimalloc = [
  "dep:mimalloc",
] # Use mimalloc as the global allocator on Linux
allocator-jemalloc = [
  "dep:tikv-jemallocator",
] # Use jemalloc as the global allocator on Linux

[dependencies]
aes = { workspace = true }
blake3 = { workspace = true }
cipher = { workspace = true }
chacha20 = { workspace = true }
ctr = { workspace = true }
curve25519-dalek = { workspace = true }
digest = { workspace = true }
ed25519-dalek = { workspace = true }
generic-array = { workspace = true, features = ["zeroize"] }
hex = { workspace = true }
k256 = { workspace = true, features = ["arithmetic", "ecdh", "hash2curve"] }
libp2p-identity = { workspace = true }
poly1305 = { workspace = true }
primitive-types = { workspace = true }
secp256k1 = { workspace = true }
serde = { workspace = true, optional = true }
serde_bytes = { workspace = true, optional = true }
sha2 = { workspace = true }
sha3 = { workspace = true }
subtle = { workspace = true }
thiserror = { workspace = true }
typenum = { workspace = true }
zeroize = { workspace = true }

hopr-crypto-random = { workspace = true }
hopr-primitive-types = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
criterion = { workspace = true }
hex-literal = { workspace = true }
lazy_static = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["serde_bytes"]

[package.metadata.cargo-shear]
ignored = ["serde_bytes"]

[[bench]]
name = "hash_bench"
harness = false

[[bench]]
name = "lioness_bench"
harness = false

[[bench]]
name = "pubkey_bench"
harness = false

[[bench]]
name = "signature_bench"
harness = false

[[bench]]
name = "vrf_bench"
harness = false

# Target-specific dependencies for memory allocators
[target.'cfg(target_os = "linux")'.dependencies]
mimalloc = { workspace = true, optional = true }
tikv-jemallocator = { workspace = true, optional = true }
