name: Branches
on:
  push:
    branches:
      - main
permissions:
  contents: read
concurrency:
  group: branches-${{ github.ref_name }}
  cancel-in-progress: false
jobs:
  coverage:
    name: Coverage
    uses: hoprnet/hopr-workflows/.github/workflows/tests.yaml@268553d7984344080e3dc65eb92778c9103af7ec # workflow-tests-v3
    with:
      source_branch: ${{ github.ref_name }}
      unit_tests: false
      integration_tests: false
      unit_coverage: true
      unconditional: true
      unit_coverage_command: "nix run .#coverage-unit"
      runner: depot-ubuntu-24.04-4
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  benchmarks:
    name: Benchmarks
    needs: coverage
    permissions:
      contents: read
      checks: write
      pull-requests: write
    uses: hoprnet/hopr-workflows/.github/workflows/benchmarks.yaml@c06be87b06af5bfcc48d98ebe95787c994e2d2c0 # workflow-benchmark-v1
    with:
      source_branch: ${{ github.ref_name }}
      runner: depot-ubuntu-24.04-4
      bencher_project: ${{ github.event.repository.name }}
      should_build: true
      should_run: true
      build_command: "nix build -L .#bench-build"
      run_command: "nix run .#bench-run"
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      bencher_api_token: ${{ secrets.BENCHER_API_TOKEN }}
      ZULIP_API_KEY: ${{ secrets.ZULIP_API_KEY }}
      ZULIP_EMAIL: ${{ secrets.ZULIP_EMAIL }}
