name: Close release
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: Version type after release
        required: true
        type: choice
        default: "patch"
        options:
          - rc
          - patch
          - minor
          - major
concurrency:
  group: release
  cancel-in-progress: false
jobs:
  build-library:
    name: Build Library
    uses: hoprnet/hopr-workflows/.github/workflows/build-library.yaml@19d69bd81be66220932b18f1a7a655b422180b4e # build-library-v3
    permissions:
      contents: read
      id-token: write
    with:
      source_branch: ${{ github.ref_name }}
      version_type: release
      architecture: x86_64-linux
      package_name: hopr-types
      runner: depot-ubuntu-24.04-4
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
  release:
    name: Close release
    needs:
      - build-library
    runs-on: depot-ubuntu-24.04
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Release version
        uses: hoprnet/hopr-workflows/actions/release-version@e8d442e87afc739ddff4736e16642744c0c565df # release-version-v5
        with:
          source_branch: ${{ github.ref_name }}
          release_type: ${{ inputs.release_type }}
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          zulip_api_key: ${{ secrets.ZULIP_API_KEY }}
          zulip_email: ${{ secrets.ZULIP_EMAIL }}
          zulip_channel: HOPRd
          zulip_topic: Releases
          github_app_private_key: ${{ secrets.GH_APP_HOPRNET_BOT_PRIVATE_KEY }}
